# -*- coding: utf-8 -*-
"""Generate a complete Fritzing part for the user's ESP32-S3-DevKitC-1 board.

The board IS the same YD-ESP32-S3 COREBOARD V1.4 as the ESP32-S3-WROOM-1 part
(27.94 x 63.39 mm incl. the protruding module antenna), so the breadboard view
is generated by the SAME breadboard_svg() as svg/ESP32-S3-WROOM-1: module_art
(scalloped module + shield) + WS2812B 5050 + CJ6107 LDO + CH343p QFN16 +
2x USB-C + NTC013 RST/BOOT buttons + 44 male header pins on the Fritzing
7.2-units-per-2.54mm hole grid (wrapped in scale(0.072)).

Pinout (J1 left / J2 right, top->bottom; connector numbering is ALIGNED with the
breadboard's WROOM-1 POS mapping so the fzp/schematic/PCB signal names always
match the breadboard face labels):
  J1 (left, top->bottom):  3V3 3V3 RST 4 5 6 7 15 16 17 18 8 3 46 9 10 11 12 13 14 5Vin GND
  J2 (right, top->bottom): GND TX RX 1 2 42 41 40 39 38 37 36 35 0 45 48 47 21 20 19 GND GND
"""

import os
import re
import zipfile
import xml.dom.minidom

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
PART_ID = "ESP32-S3-DevKitC-1_1"
TITLE = "ESP32-S3-DevKitC-1"

BB_SVG = "svg.breadboard.%s_breadboard.svg" % PART_ID
SCHEM_SVG = "svg.schematic.%s_schematic.svg" % PART_ID
PCB_SVG = "svg.pcb.%s_pcb.svg" % PART_ID
ICON_SVG = "svg.icon.%s_icon.svg" % PART_ID
FZP = "part.%s.fzp" % PART_ID
FZPZ = "ESP32-S3-DevKitC-1.fzpz"

BB_REF = "breadboard/%s_breadboard.svg" % PART_ID
SCHEM_REF = "schematic/%s_schematic.svg" % PART_ID
PCB_REF = "pcb/%s_pcb.svg" % PART_ID
ICON_REF = "icon/%s_icon.svg" % PART_ID

# --------------------------------------------------------------------------
# ---- Header pinout (J1 left / J2 right, top->bottom) ----
# The silkscreen names printed on the real YD board. Used everywhere so the
# breadboard face labels, schematic names, PCB pads and fzp connector names are
# all consistent.
HEADER_L = ["3V3", "3V3", "RST", "4", "5", "6", "7", "15", "16", "17", "18",
            "8", "3", "46", "9", "10", "11", "12", "13", "14", "5Vin", "GND"]
HEADER_R = ["GND", "TX", "RX", "1", "2", "42", "41", "40", "39", "38", "37",
            "36", "35", "0", "45", "48", "47", "21", "20", "19", "GND", "GND"]

# ---- Connector model (ALIGNED with the breadboard's WROOM-1 POS mapping) ----
# connector0..40 = the 41 module-signal header positions (POS), connector41..43
# = the 3 extra power pins J1-2 3V3 / J1-21 5Vin / J2-22 GND (EXTRA). The name
# of connector i = the header silkscreen label at its position, so the fzp /
# schematic / PCB signal names ALWAYS match the breadboard's face labels.
POS = [("R", 0), ("L", 0), ("L", 2), ("L", 3), ("L", 4), ("L", 5), ("L", 6),
       ("L", 7), ("L", 8), ("L", 9), ("L", 10), ("L", 11), ("R", 19), ("R", 18),
       ("L", 12), ("L", 13), ("L", 14), ("L", 15), ("L", 16), ("L", 17),
       ("L", 18), ("L", 19), ("R", 17), ("R", 16), ("R", 15), ("R", 14),
       ("R", 13), ("R", 12), ("R", 11), ("R", 10), ("R", 9), ("R", 8),
       ("R", 7), ("R", 6), ("R", 5), ("R", 2), ("R", 1), ("R", 3), ("R", 4),
       ("L", 21), ("R", 20)]
EXTRA = {41: ("L", 1), 42: ("L", 20), 43: ("R", 21)}   # J1-2 3V3 / J1-21 5Vin / J2-22 GND

# header (col,row) -> connector index
HDR2CN = {}
for _cn, _pos in enumerate(POS):
    HDR2CN[_pos] = _cn
HDR2CN.update({p: cn for cn, p in EXTRA.items()})
# header row -> connector index for each column (schematic/PCB left/right order)
J1_CN = [HDR2CN[("L", r)] for r in range(22)]
J2_CN = [HDR2CN[("R", r)] for r in range(22)]


def cn_name(cn):
    """Signal name carried by connector cn = the header silkscreen label at its
    position (identical to the breadboard face label)."""
    col, row = POS[cn] if cn < 41 else EXTRA[cn]
    return (HEADER_L if col == "L" else HEADER_R)[row]


# full-name descriptions (for the fzp <description>)
DESC = {
    "3V3": "3.3V power", "5V": "5V power (from USB)", "5Vin": "5V power input (from USB)",
    "GND": "Ground",
    "RST": "Reset / EN (active low)", "TX": "UART TX (GPIO43)", "RX": "UART RX (GPIO44)",
    "0": "GPIO0", "1": "GPIO1", "2": "GPIO2", "3": "GPIO3", "4": "GPIO4",
    "5": "GPIO5", "6": "GPIO6", "7": "GPIO7", "8": "GPIO8", "9": "GPIO9",
    "10": "GPIO10", "11": "GPIO11", "12": "GPIO12", "13": "GPIO13", "14": "GPIO14",
    "15": "GPIO15", "16": "GPIO16", "17": "GPIO17", "18": "GPIO18",
    "19": "GPIO19", "20": "GPIO20", "21": "GPIO21", "35": "GPIO35",
    "36": "GPIO36", "37": "GPIO37", "38": "GPIO38 (RGB LED)", "39": "GPIO39",
    "40": "GPIO40", "41": "GPIO41", "42": "GPIO42", "45": "GPIO45",
    "46": "GPIO46", "47": "GPIO47", "48": "GPIO48",
}

# board geometry (100 units = 2.54 mm). Portrait: 57.15mm tall x 27.94mm wide
W, H = 1100, 2250             # 27.94 x 57.15 mm
PIN_PITCH = 100
N = 22
# two vertical pin columns on the long (left/right) edges, 25.4 mm apart
# centre-to-centre (1000 units), matching the breadboard and icon columns
# (left column 1.27 mm / right column 26.67 mm from the left edge)
PX_L, PX_R = 50, W - 50
PY0 = (H - (N - 1) * PIN_PITCH) / 2   # 75


def _pin_y(i):
    return PY0 + i * PIN_PITCH


def module_art(S, ox, oy, grad):
    """Emit the ESP32-S3-WROOM-1 module artwork (dark scalloped PCB board +
    meander antenna + two gold feed contacts + metallic shield + text/QR code +
    gold castellation pads), scaled by S (the icon is 1 unit = 1 mm; the
    breadboard uses S = 39.37) and translated by (ox, oy). The antenna is at
    the TOP of the module so it can protrude above the host board edge."""
    L = []
    r = 0.275 * S
    # dark PCB board, scalloped with a real 0.55 mm semicircular castellation
    # notch cut into every edge (no stroke, bbox exactly 18S x 25S)
    bd = ['  <path d="M %.2f %.2f' % (ox, oy), ' L %.2f %.2f' % (ox + 18 * S, oy)]
    for i in range(13, -1, -1):
        yc = (23.5 - i * 1.27) * S
        bd.append(' L %.2f %.2f A %.3f %.3f 0 0 0 %.2f %.2f' % (ox + 18 * S, oy + yc - r, r, r, ox + 18 * S, oy + yc + r))
    bd.append(' L %.2f %.2f' % (ox + 18 * S, oy + 25 * S))
    for i in range(11, -1, -1):
        xc = (0.96 + i * 1.38 + 0.45) * S
        bd.append(' L %.2f %.2f A %.3f %.3f 0 0 0 %.2f %.2f' % (ox + xc + r, oy + 25 * S, r, r, ox + xc - r, oy + 25 * S))
    bd.append(' L %.2f %.2f' % (ox, oy + 25 * S))
    for i in range(0, 14):
        yc = (23.5 - i * 1.27) * S
        bd.append(' L %.2f %.2f A %.3f %.3f 0 0 0 %.2f %.2f' % (ox, oy + yc + r, r, r, ox, oy + yc - r))
    bd.append(' L %.2f %.2f Z" fill="#2b2b2b"/>' % (ox, oy))
    L.append(' '.join(bd) + '\n')
    # meander antenna (borrowed from ESP-12F icon, mirrored L/R, top of module)
    ant = [(36.961, 10.969), (28.617, 10.969), (28.617, 3.269), (23.357, 3.269), (23.357, 10.969),
           (15.077, 10.969), (15.077, 3.269), (9.961, 3.269), (9.961, 15.286), (8.741, 15.286),
           (8.741, 3.269), (3.251, 3.269), (3.251, 15.289), (2.049, 15.289), (2.049, 2.049),
           (16.297, 2.049), (16.297, 9.749), (22.137, 9.749), (22.137, 2.049), (29.837, 2.049),
           (29.837, 9.749), (35.741, 9.749), (35.741, 2.049), (43.301, 2.049), (43.301, 15.289),
           (42.081, 15.289), (42.081, 3.269), (36.961, 3.269)]
    s = 0.40
    pts = ["%.2f,%.2f" % (ox + ((45.35 - x - 2.049) * s + 0.75) * S, oy + ((y - 2.049) * s + 0.5) * S)
           for (x, y) in ant]
    L.append('  <polygon points="%s" fill="#9aa0a6"/>\n' % " ".join(pts))
    # two gold feed contacts at the bottom of the two rightmost antenna runs
    L.append('  <circle cx="%.2f" cy="%.2f" r="%.3f" fill="#e3b23c"/>\n' % (ox + 14.33 * S, oy + 5.79 * S, 0.24 * S))
    L.append('  <circle cx="%.2f" cy="%.2f" r="%.3f" fill="#e3b23c"/>\n' % (ox + 17.01 * S, oy + 5.80 * S, 0.24 * S))
    # white metal shield (square corners, metallic gradient, no stroke)
    L.append('  <rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" fill="url(#%s)"/>\n'
             % (ox + 1.1 * S, oy + 6.35 * S, 15.8 * S, 17.6 * S, grad))
    L.append('  <text x="%.2f" y="%.2f" font-size="%.2f" font-weight="bold" fill="#111111" text-anchor="middle" font-family="Arial">ESPRESSIF</text>\n'
             % (ox + 9 * S, oy + 12.2 * S, 2.3 * S))
    L.append('  <text x="%.2f" y="%.2f" font-size="%.2f" fill="#333333" text-anchor="middle" font-family="Arial">ESP32-S3-WROOM-1</text>\n'
             % (ox + 9 * S, oy + 14.8 * S, 1.6 * S))
    L.append('  <text x="%.2f" y="%.2f" font-size="%.2f" fill="#555555" text-anchor="middle" font-family="Arial">乐鑫信息科技</text>\n'
             % (ox + 9 * S, oy + 16.8 * S, 1.2 * S))
    # QR code (bottom-right of the shield)
    L.append('  <g fill="#111111">\n')
    for (qx, qy) in [(12.6, 17.6), (13.8, 17.6), (15.0, 17.6), (12.6, 18.8), (13.8, 18.8),
                     (12.6, 20.0), (15.0, 20.0), (13.8, 20.0), (15.0, 18.8), (15.0, 19.4), (12.6, 19.4)]:
        L.append('   <rect x="%.2f" y="%.2f" width="%.2f" height="%.2f"/>\n' % (ox + qx * S, oy + qy * S, 1.0 * S, 1.0 * S))
    L.append('  </g>\n')
    # gold edge pads, each with a matching CONCAVE notch on its outer end
    L.append('  <g fill="#e3b23c">\n')
    for i in range(14):
        yc = (23.5 - i * 1.27) * S
        L.append('   <path d="M %.2f %.2f L %.2f %.2f L %.2f %.2f A %.3f %.3f 0 0 1 %.2f %.2f L %.2f %.2f L %.2f %.2f Z"/>\n'
                 % (ox + 0.45 * S, oy + yc - 0.45 * S, ox, oy + yc - 0.45 * S, ox, oy + yc - r, r, r, ox, oy + yc + r,
                    ox, oy + yc + 0.45 * S, ox + 0.45 * S, oy + yc + 0.45 * S))
        L.append('   <path d="M %.2f %.2f L %.2f %.2f L %.2f %.2f A %.3f %.3f 0 0 0 %.2f %.2f L %.2f %.2f L %.2f %.2f Z"/>\n'
                 % (ox + 17.55 * S, oy + yc - 0.45 * S, ox + 18 * S, oy + yc - 0.45 * S, ox + 18 * S, oy + yc - r, r, r,
                    ox + 18 * S, oy + yc + r, ox + 18 * S, oy + yc + 0.45 * S, ox + 17.55 * S, oy + yc + 0.45 * S))
    for i in range(12):
        xc = (0.96 + i * 1.38 + 0.45) * S
        L.append('   <path d="M %.2f %.2f L %.2f %.2f L %.2f %.2f A %.3f %.3f 0 0 1 %.2f %.2f L %.2f %.2f L %.2f %.2f Z"/>\n'
                 % (ox + xc - 0.45 * S, oy + 24.55 * S, ox + xc - 0.45 * S, oy + 25 * S, ox + xc - r, oy + 25 * S, r, r,
                    ox + xc + r, oy + 25 * S, ox + xc + 0.45 * S, oy + 25 * S, ox + xc + 0.45 * S, oy + 24.55 * S))
    L.append('  </g>\n')
    return "".join(L)


# --------------------------------------------------------------------------
# USB Type-C (16-pin) connector art, reused verbatim from the TypeC16Pin part
# (svg/TypeC16Pin/svg.icon.TypeC16Pin_d89a481c23a1ca4ff437422a227ed0bb_1_icon.svg).
# The icon artwork is a real 8.94 mm wide receptacle drawn at ~1 unit =
# 0.3528 mm (content bbox 25.34 x 21.64 units == 8.94 x 7.63 mm). We lift the
# inner drawing group, strip the now-duplicate element ids, and re-emit it
# scaled for the breadboard. The gold contact pads are at the BOTTOM of the
# artwork, so we drop the connector onto the board edge with that edge at
# `bottom_y` (the plug face sits at the board edge).
_TYPEC_PATH = os.path.join(OUT_DIR, "..", "TypeC16Pin",
                           "svg.icon.TypeC16Pin_d89a481c23a1ca4ff437422a227ed0bb_1_icon.svg")
try:
    with open(_TYPEC_PATH, encoding="utf-8") as _tf:
        _typec_src = _tf.read()
    _tm = re.search(r'(<g\s+id="g40446"[^>]*>.*</g>)\s*</svg>', _typec_src, re.S)
    _TYPEC_ART = re.sub(r'\s+id="[^"]*"', '', _tm.group(1))
except Exception:
    _TYPEC_ART = None


def typec_art(cx, bottom_y, width_mm=8.94):
    """Emit the TypeC16Pin USB-C connector art, centred horizontally at cx,
    `width_mm` wide, sitting at the board's bottom edge (`bottom_y`). The
    artwork is rotated 180° about its own centre so the plug opening faces
    DOWN (out of the board edge) while the connector stays in the same box at
    the bottom of the board. Content bbox is 25.34 x 21.64 units = 8.94 x
    7.63 mm at 1:1, so the breadboard scale is width_mm/8.94 * 39.37."""
    s = width_mm * 39.37 / 25.34
    ox = cx - (25.34 / 2.0) * s
    oy = bottom_y - 21.64 * s
    rcx = (25.34 / 2.0) * s      # art centre in the scaled (breadboard) space
    rcy = (21.64 / 2.0) * s
    if _TYPEC_ART is None:
        return ('  <rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" fill="#333333" '
                'stroke="#999999" stroke-width="5"/>\n' % (ox, oy, 25.34 * s, 21.64 * s))
    return ('  <g transform="translate(%.2f %.2f) rotate(180 %.2f %.2f) scale(%.5f)">\n'
            '%s\n  </g>\n' % (ox, oy, rcx, rcy, s, _TYPEC_ART))

# --------------------------------------------------------------------------
# WS2812B 5050 RGB LED art, reused from the WS2812B/5050 part's breadboard view
# (svg/WS2812B/5050/svg.breadboard.WS2812B_5050_1_breadboard.svg). The LED body
# (4 gray SMT pads + dark die + gold bond wires + light lens) is authored at
# 1 unit = 0.3528 mm, so the same 13.89 scale factor as the USB-C art places it
# at true size on the YD board (5.0 x 5.0 mm). The artwork is rotated 180° so
# VDD (bottom-right on the bare 5050) ends up at the top-right corner, i.e. to
# the RIGHT of header pin 9 on the assembled board. Duplicate ids are stripped.
_WS2812_PATH = os.path.join(OUT_DIR, "..", "WS2812B", "5050",
                            "svg.breadboard.WS2812B_5050_1_breadboard.svg")
_WS2812_ART = None
try:
    _wdoc = xml.dom.minidom.parse(_WS2812_PATH)
    _ledg = None
    for _g in _wdoc.getElementsByTagName("g"):
        if _g.getAttribute("transform") == "translate(10.8000,21.6000) rotate(90) translate(-10.8000,-21.6000)":
            _ledg = _g
            break
    if _ledg is not None:
        for _e in _ledg.getElementsByTagName("*"):
            if _e.hasAttribute("id"):
                _e.removeAttribute("id")
        _WS2812_ART = _ledg.toxml()
except Exception:
    _WS2812_ART = None


def ws2812_art(cx, cy):
    """Emit the realistic WS2812B 5050 LED art centred at (cx, cy), scaled to
    true size (5.0 mm = 197 units at 39.37 units/mm), rotated 180° so the VDD
    pad sits at the top-right (toward header pin 9)."""
    s = 13.89
    if _WS2812_ART is None:
        return ('  <rect x="%.0f" y="%.0f" width="197" height="197" rx="12" fill="#1a1a1a" '
                'stroke="#333333" stroke-width="4"/>\n' % (cx - 98, cy - 98))
    return ('  <g transform="translate(%d %d) rotate(180) scale(%.5f) translate(-10.8 -21.6)">\n'
            '%s\n  </g>\n' % (cx, cy, s, _WS2812_ART))


def breadboard_svg():
    """Breadboard view = the user's YD-ESP32-S3 COREBOARD V1.4 dev board.
    Total board size 27.94 x 63.39 mm: the black PCB is 57.15 mm tall with
    SQUARE corners, and the ESP32-S3-WROOM-1 module (drawn with the ICON
    artwork via module_art) sits at the top with its antenna protruding
    6.24 mm above the PCB edge (57.15 + 6.24 = 63.39 mm). The internal
    coordinate space uses 100 units = 2.54 mm; the whole board is wrapped in a
    scale(0.072) group so the final SVG is at the Fritzing breadboard hole
    grid (7.2 units per 2.54 mm) and the two 22-pin header columns (25.4 mm
    apart, centre-to-centre) land on breadboard holes. Layout measured from
    the vendor "ESP32-S3-Metric" placement drawing: module top, WS2812 RGB +
    LDO below, RST/BOOT on the right, CH343P + 2 USB-C at the bottom.
    44 male header pins total: 41 connectors mapped from the module's
    J1/J2 positions that carry a matching signal, plus 3 breadboard-only
    connectors (connector41..43) for the extra power pins J1-2 3V3, J1-21
    5Vin and J2-22 GND. The visible labels are the header SILKSCREEN names
    (J1/J2), rotated vertically (left +90 deg CW reading top->down, right
    -90 deg CCW). No mounting holes (the real board has none)."""
    L = []
    L.append('<?xml version="1.0" encoding="utf-8"?>\n')
    W = 1100                      # 27.94 mm (internal 100 units = 2.54 mm)
    HH = 2496                     # 63.39 mm (PCB 57.15 + 6.24 antenna)
    # Fritzing breadboard hole grid = 7.2 units per 2.54 mm hole. Our internal
    # 100-units-per-2.54mm space must be scaled by 7.2/100 = 0.072 so pins land
    # on breadboard holes (verified vs arduino_Uno/NodeMCU core parts + the
    # core breadboard.svg: holes at 7.2 pitch).
    BB_SCALE = 7.2 / 100.0        # 0.072
    PCB_TOP = 246                 # antenna protrusion above the PCB edge
    PCB_H = 2250                  # 57.15 mm PCB
    L.append('<svg xmlns="http://www.w3.org/2000/svg" width="27.94mm" height="63.39mm" viewBox="0 0 %.1f %.1f">\n' % (W * BB_SCALE, HH * BB_SCALE))
    L.append(' <defs>\n')
    L.append('  <linearGradient id="bbShield" x1="0" y1="0" x2="0" y2="1">\n')
    L.append('   <stop offset="0" stop-color="#e2e2e2"/>\n')
    L.append('   <stop offset="0.45" stop-color="#b4b4b4"/>\n')
    L.append('   <stop offset="1" stop-color="#7c7c7c"/>\n')
    L.append('  </linearGradient>\n')
    L.append(' </defs>\n')
    L.append(' <g id="breadboard" transform="scale(%g)">\n' % BB_SCALE)
    # black PCB with SQUARE corners (user: the 4 corners are right angles)
    L.append('  <rect x="0" y="%d" width="%d" height="%d" fill="#262626" stroke="#000000" stroke-width="6"/>\n' % (PCB_TOP, W, PCB_H))
    # ESP32-S3-WROOM-1 module at the TOP, antenna protruding above the PCB edge
    # (the module is drawn with the exact ICON artwork, scaled to the board)
    L.append(module_art(39.37, 196.0, 0.0, "bbShield"))
    # CJ6107A33GW 3.3V LDO (SOT-223) right of pins 8/18 + WS2812B 5050 RGB LED
    # (right of pins 9/10). SOT-223 drawn horizontally then rotated 90° CW about
    # its centre so its 3 gull-wing PINS (on the left after rotation) align in X
    # with the WS2812B 5050's left pads (x=201); the heatsink tab ends up on the
    # right. 6.5 x 3.5 mm = 256 x 138 units.
    L.append(ws2812_art(302, 1771))
    CX, CY, BW, BH = 291, 1371, 256, 138
    L.append('  <g transform="rotate(90 %d %d)">\n' % (CX, CY))
    L.append('  <rect x="%d" y="%d" width="%d" height="%d" rx="8" fill="#303030" stroke="#4a4a4a" stroke-width="4"/>\n'
             % (CX - BW // 2, CY - BH // 2, BW, BH))
    # large heatsink tab (top of the unrotated part -> right after rotation)
    L.append('  <rect x="%d" y="%d" width="200" height="46" rx="4" fill="#8c8c8c"/>\n' % (CX - 100, CY - BH // 2 - 48))
    # 3 gull-wing pins at the bottom (-> left after rotation)
    for dx in (-90, 0, 90):
        L.append('  <rect x="%d" y="%d" width="50" height="38" rx="4" fill="#8c8c8c"/>\n' % (CX + dx - 25, CY + BH // 2 + 2))
    L.append('  <text x="%d" y="%d" font-size="28" fill="#ffffff" text-anchor="middle" font-family="DroidSans">CJ6107A33GW</text>\n' % (CX, CY + 8))
    L.append('  </g>\n')
    # RST + BOOT buttons on the right side: RST at the height between pins 38/39
    # (y 1171), BOOT between pins 36/37 (y 1371). Text (font 52 = pin-label size,
    # same as "37") sits to the RIGHT of each button, vertical reading top->down.
    # Cluster kept left of the right-column labels (x>=968).
    #
    # The button artwork is the NTC013-AT1J-A160T 4.2x3.2mm SMD tact switch,
    # copied from the ESP32-S2-DevKitC-1 Fritzing part breadboard (its RESET
    # button): light-grey housing + dark round actuator with a white shine +
    # 4 corner feet + 2 light-grey J-lead pads + dark detail bars. Copied at
    # scale 0.60 so the housing (~90x70 units) fits between the pin rows and
    # stays left of the RST/BOOT labels at x=915 (housing right edge ~895).
    def ntc013_btn(cx, cy):
        """Emit one NTC013 tact switch scaled 0.60 about (cx, cy). Exact
        geometry (relative to the housing centre) from the S2-DevKitC RESET
        button: housing 151x116, actuator ~74x76 centred, feet 8x13 at the
        corners, J-lead pads 26x54 sticking out the sides, 4 dark bars."""
        L.append('  <g transform="translate(%d %d) scale(0.60)">\n' % (cx, cy))
        # housing (light grey)
        L.append('  <rect x="-75.5" y="-58" width="151" height="116" fill="#cccccc"/>\n')
        # 4 dark feet at the corners
        L.append('  <rect x="-78.5" y="-31" width="8" height="13" fill="#333333"/>\n')
        L.append('  <rect x="66.5" y="-31" width="8" height="13" fill="#333333"/>\n')
        L.append('  <rect x="-78.5" y="15" width="8" height="13" fill="#333333"/>\n')
        L.append('  <rect x="66.5" y="15" width="8" height="13" fill="#333333"/>\n')
        # 2 light-grey J-lead pads sticking out left/right
        L.append('  <rect x="-102.5" y="-28" width="26" height="54" fill="#e6e6e6"/>\n')
        L.append('  <rect x="74.5" y="-28" width="26" height="54" fill="#e6e6e6"/>\n')
        # 4 dark detail bars
        L.append('  <rect x="-76.5" y="-58" width="21" height="8" fill="#333333"/>\n')
        L.append('  <rect x="53.5" y="-58" width="21" height="8" fill="#333333"/>\n')
        L.append('  <rect x="-76.5" y="0" width="21" height="8" fill="#333333"/>\n')
        L.append('  <rect x="53.5" y="0" width="21" height="8" fill="#333333"/>\n')
        # round actuator (dark) with white shine arc
        L.append('  <ellipse cx="-2.5" cy="-1" rx="37.766" ry="36.967" fill="#333333" stroke="#1a1a1a" stroke-width="3.03"/>\n')
        L.append('  <path d="m -15.02,-36.72 c 5.29,-2.70 7.93,-2.70 13.19,-2.70 13.19,0 23.78,5.40 29.07,16.19" fill="none" stroke="#ffffff" stroke-width="3.03"/>\n')
        L.append('  </g>\n')
    for cy, lab in ((1171, "RST"), (1371, "BOOT")):
        bx, tx = 788, 863
        ntc013_btn(bx, cy)
        L.append('  <text x="%d" y="%d" font-size="52" fill="#ffffff" text-anchor="middle" font-family="DroidSans" transform="rotate(90 %d %d)">%s</text>\n' % (tx, cy, tx, cy, lab))
    # CH343P USB-UART bridge (QFN16, left of header pins 21/47). 3.5 x 3.5 mm
    # body with 16 edge pads (4 per side) + a central exposed thermal pad.
    # Moved down 1 char (52) from (798, 1867).
    QX, QY, QB = 798, 1919, 138
    L.append('  <rect x="%d" y="%d" width="%d" height="%d" fill="#303030" stroke="#4a4a4a" stroke-width="4"/>\n'
             % (QX - QB // 2, QY - QB // 2, QB, QB))
    # 16 edge pads, 4 per side (straddling the body edges)
    for dx in (-45, -15, 15, 45):
        L.append('  <rect x="%d" y="%d" width="16" height="32" fill="#8c8c8c"/>\n' % (QX + dx - 8, QY - QB // 2 - 16))   # top
        L.append('  <rect x="%d" y="%d" width="16" height="32" fill="#8c8c8c"/>\n' % (QX + dx - 8, QY + QB // 2 - 16))   # bottom
    for dy in (-45, -15, 15, 45):
        L.append('  <rect x="%d" y="%d" width="32" height="16" fill="#8c8c8c"/>\n' % (QX - QB // 2 - 16, QY + dy - 8))   # left
        L.append('  <rect x="%d" y="%d" width="32" height="16" fill="#8c8c8c"/>\n' % (QX + QB // 2 - 16, QY + dy - 8))   # right
    # centre exposed thermal pad
    L.append('  <rect x="%d" y="%d" width="48" height="48" fill="#555555"/>\n' % (QX - 24, QY - 24))
    L.append('  <text x="%d" y="%d" font-size="20" fill="#cccccc" text-anchor="middle" font-family="DroidSans">CH343p</text>\n' % (QX, QY - QB // 2 - 22))
    # 2x USB Type-C at the bottom edge (left = OTG native USB, right = CH343p
    # UART), drawn with the real TypeC16Pin connector art (plug face at the
    # board edge, gold pads on the bottom edge of the artwork)
    L.append(typec_art(300, HH, 8.94))   # OTG
    L.append(typec_art(790, HH, 8.94))   # UART
    L.append('  <text x="300" y="2130" font-size="20" fill="#aaaaaa" text-anchor="middle" font-family="DroidSans">OTG</text>\n')
    L.append('  <text x="790" y="2130" font-size="20" fill="#aaaaaa" text-anchor="middle" font-family="DroidSans">UART</text>\n')
    # ---- pins: two 22-pin columns, 25.4 mm apart (centre-to-centre) ----
    PX_L, PX_R = 50, W - 50       # (W-50) - 50 = 1000 units = 25.4 mm
    PY0 = PCB_TOP + 75            # top pin centre on the PCB; pitch 100 = 2.54 mm
    # header silkscreen names printed on the actual YD board (J1 left / J2 right,
    # top->bottom). Labels are shown rotated vertically next to each pin.
    HEADER_L = ["3V3", "3V3", "RST", "4", "5", "6", "7", "15", "16", "17", "18",
                "8", "3", "46", "9", "10", "11", "12", "13", "14", "5Vin", "GND"]
    HEADER_R = ["GND", "TX", "RX", "1", "2", "42", "41", "40", "39", "38", "37",
                "36", "35", "0", "45", "48", "47", "21", "20", "19", "GND", "GND"]
    # connector index -> (col, row); row 0 = top, 21 = bottom.
    # Each module pin sits at the header pin that carries the same net:
    # J1 (left) = module left+bottom side, J2 (right) = module right side.
    POS = [("R", 0), ("L", 0), ("L", 2), ("L", 3), ("L", 4), ("L", 5), ("L", 6),
           ("L", 7), ("L", 8), ("L", 9), ("L", 10), ("L", 11), ("R", 19), ("R", 18),
           ("L", 12), ("L", 13), ("L", 14), ("L", 15), ("L", 16), ("L", 17),
           ("L", 18), ("L", 19), ("R", 17), ("R", 16), ("R", 15), ("R", 14),
           ("R", 13), ("R", 12), ("R", 11), ("R", 10), ("R", 9), ("R", 8),
           ("R", 7), ("R", 6), ("R", 5), ("R", 2), ("R", 1), ("R", 3), ("R", 4),
           ("L", 21), ("R", 20)]

    def header_name(col, row):
        return (HEADER_L if col == "L" else HEADER_R)[row]

    # vertical labels: left rotate +90° (CW, reads top->down), right -90° (CCW).
    # Narrow sans font (DroidSans) + close to the pins, like the real board's
    # silkscreen.
    LBL_OFF = 36
    for i in range(41):
        col, row = POS[i]
        x = PX_L if col == "L" else PX_R
        y = PY0 + row * 100
        L.append('  <circle cx="%d" cy="%d" r="26" fill="#b8b8b8" stroke="#6a6a6a" stroke-width="5" id="connector%dpin"/>\n' % (x, y, i))
        lx = x + LBL_OFF if col == "L" else x - LBL_OFF
        rot = 90 if col == "L" else -90
        L.append('  <text x="%d" y="%d" font-size="52" fill="#ffffff" text-anchor="middle" font-family="DroidSans" transform="rotate(%d %d %d)">%s</text>\n'
                 % (lx, y, rot, lx, y, header_name(col, row)))
    # J1-2 3V3, J1-21 5Vin and J2-22 GND are REAL male header pins on the YD
    # board (extra power pins that don't carry a module signal). Give each a
    # breadboard-only connector (connector41..43) so its hole turns green and it
    # is routable on the breadboard (same pattern as core part m40-1100300).
    for cn, (col, row) in zip((41, 42, 43), (("L", 1), ("L", 20), ("R", 21))):
        x = PX_L if col == "L" else PX_R
        y = PY0 + row * 100
        L.append('  <circle cx="%d" cy="%d" r="26" fill="#b8b8b8" stroke="#6a6a6a" stroke-width="5" id="connector%dpin"/>\n' % (x, y, cn))
        lx = x + LBL_OFF if col == "L" else x - LBL_OFF
        rot = 90 if col == "L" else -90
        L.append('  <text x="%d" y="%d" font-size="52" fill="#ffffff" text-anchor="middle" font-family="DroidSans" transform="rotate(%d %d %d)">%s</text>\n'
                 % (lx, y, rot, lx, y, header_name(col, row)))
    L.append(' </g>\n')
    L.append('</svg>\n')
    return "".join(L)


def schematic_svg():
    """44-pin IC-box symbol: J1 pins on the left, J2 pins on the right. Connector
    numbering matches the breadboard's POS mapping, names sit INSIDE the box
    (clear of the pin lines)."""
    L = []
    L.append('<?xml version="1.0" encoding="utf-8"?>\n')
    L.append('<svg xmlns="http://www.w3.org/2000/svg" width="340" height="300" viewBox="0 0 340 300">\n')
    L.append(' <g id="schematic">\n')
    L.append('  <rect x="110" y="20" width="120" height="260" fill="#FFFFFF" stroke="#000000" stroke-width="1.6"/>\n')
    # body text (vertical)
    L.append('  <text x="170" y="155" font-size="12" fill="#000000" text-anchor="middle" transform="rotate(90 170 155)">ESP32-S3-DevKitC-1</text>\n')
    topy, boty = 26, 274
    step = (boty - topy) / (N - 1)
    # left pins = J1 column (connector order from the breadboard POS mapping);
    # name INSIDE the box (x=120, away from the line)
    for r in range(N):
        y = topy + r * step
        cn = J1_CN[r]
        L.append('  <line class="pin" id="connector%dpin" connectorname="%d" x1="110" y1="%.2f" x2="86" y2="%.2f" stroke="#787878" stroke-width="1.0"/>\n' % (cn, cn, y, y))
        L.append('  <rect class="terminal" id="connector%dterminal" x="86" y="%.2f" width="0.0001" height="0.0001" fill="none"/>\n' % (cn, y))
        L.append('  <text x="120" y="%.2f" font-size="8.5" fill="#333333" text-anchor="start" font-family="DroidSans">%s</text>\n' % (y + 3, HEADER_L[r]))
    # right pins = J2 column (connector order from the breadboard POS mapping)
    for r in range(N):
        y = topy + r * step
        cn = J2_CN[r]
        L.append('  <line class="pin" id="connector%dpin" connectorname="%d" x1="230" y1="%.2f" x2="254" y2="%.2f" stroke="#787878" stroke-width="1.0"/>\n' % (cn, cn, y, y))
        L.append('  <rect class="terminal" id="connector%dterminal" x="254" y="%.2f" width="0.0001" height="0.0001" fill="none"/>\n' % (cn, y))
        L.append('  <text x="220" y="%.2f" font-size="8.5" fill="#333333" text-anchor="end" font-family="DroidSans">%s</text>\n' % (y + 3, HEADER_R[r]))
    L.append(' </g>\n')
    L.append('</svg>\n')
    return "".join(L)


def pcb_svg():
    """2x22 THROUGH-HOLE header footprint (left/right columns) + module outline
    WITH its antenna PROTRUDING ABOVE the board top edge (like the breadboard:
    the module's top ~6 mm antenna zone sticks out 6.24 mm past the PCB edge).
    Drawn as a SOLID keep-out ring around the protrusion + a label (no meander
    shape) so the RF area is clear for component placement.
    Through-hole pads: HOLLOW copper rings on BOTH sides - copper0 nested inside
    copper1 (dip_8_300mil style: fill="none" + thick copper stroke), each pad
    outer radius 40 u (1.02 mm), drill 20 u (0.51 mm)."""
    L = []
    L.append('<?xml version="1.0" encoding="utf-8"?>\n')
    ANT_PROTRUDE = 246.0          # 6.24 mm antenna protrusion above the PCB edge
    # viewBox = the exact board+antenna extent: 1100 x 2496 units = 27.94 mm x
    # 63.39 mm (57.15 mm board + 6.24 mm protruding antenna, antenna at y<0).
    # width/height = the same size in mm, so the board stays 27.94 x 57.15 mm
    # and the pin columns (PX_L=50 / PX_R=1050) are 25.4 mm apart.
    VB_X, VB_Y, VB_W, VB_H = 0, -int(ANT_PROTRUDE), W, H + int(ANT_PROTRUDE)
    L.append('<svg xmlns="http://www.w3.org/2000/svg" width="27.94mm" height="63.39mm" viewBox="%d %d %d %d">\n'
             % (VB_X, VB_Y, VB_W, VB_H))
    L.append(' <g id="silkscreen">\n')
    # board outline: SQUARE corners, full board - identical to the breadboard PCB
    L.append('  <rect x="0" y="0" width="%d" height="%d" fill="none" stroke="#FFFFFF" stroke-width="6"/>\n' % (W, H))
    # module outline at the breadboard position: on-board body only (the module
    # is 18 mm wide x 25.5 mm tall at 39.37 u/mm, its antenna protrudes
    # 6.24 mm = 246 u above the top edge -> on-board height 758)
    L.append('  <rect x="196" y="0" width="%.1f" height="758" fill="none" stroke="#FFFFFF" stroke-width="5"/>\n' % (18.0 * 39.37))
    # antenna PROTRUDES ABOVE the board top edge (y<0), exactly like the
    # breadboard: SOLID keep-out ring around the protrusion + label.
    L.append('  <rect x="196" y="%.1f" width="%.1f" height="%.1f" fill="none" stroke="#FFFFFF" stroke-width="5"/>\n'
             % (-ANT_PROTRUDE, 18.0 * 39.37, ANT_PROTRUDE))
    L.append('  <text x="%.1f" y="35" font-size="40" fill="#FFFFFF" text-anchor="middle" font-family="DroidSans">ANTENNA</text>\n'
             % (196.0 + 18.0 * 39.37 / 2.0))
    L.append(' </g>\n')
    # through-hole pads on BOTH sides: copper0 nested inside copper1 (avoids the
    # new-parts-editor "separate copper0/copper1" error). Hollow copper ring per
    # pad (core THT style): r=30 + stroke-width=20 -> annulus 20..40 u (drill
    # 0.51 mm / outer 1.02 mm).
    L.append(' <g id="copper1">\n')
    L.append('  <g id="copper0">\n')
    for r in range(N):
        y = _pin_y(r)
        L.append('   <circle cx="%d" cy="%.1f" r="30" id="connector%dpin" fill="none" stroke="rgb(255,191,0)" stroke-width="20"/>\n' % (PX_L, y, J1_CN[r]))
        L.append('   <circle cx="%d" cy="%.1f" r="30" id="connector%dpin" fill="none" stroke="rgb(255,191,0)" stroke-width="20"/>\n' % (PX_R, y, J2_CN[r]))
    L.append('  </g>\n')
    L.append(' </g>\n')
    L.append('</svg>\n')
    return "".join(L)


def icon_svg():
    """Dev-board icon = the same YD-ESP32-S3 COREBOARD as the breadboard:
    dark PCB (square corners, 57.15 mm) + ESP32-S3-WROOM-1 module (module_art)
    at the top with its antenna protruding 6.24 mm, 2x USB-C at the bottom
    edge. Drawn at true mm scale (27.94 x 63.39 mm) so it matches the
    breadboard."""
    L = []
    L.append('<?xml version="1.0" encoding="UTF-8"?>\n')
    L.append('<svg xmlns="http://www.w3.org/2000/svg" width="27.94mm" height="63.39mm" viewBox="0 0 27.94 63.39">\n')
    L.append(' <defs>\n')
    L.append('  <linearGradient id="shieldMetal" x1="0" y1="0" x2="0" y2="1">\n')
    L.append('   <stop offset="0" stop-color="#e2e2e2"/>\n')
    L.append('   <stop offset="0.45" stop-color="#b4b4b4"/>\n')
    L.append('   <stop offset="1" stop-color="#7c7c7c"/>\n')
    L.append('  </linearGradient>\n')
    L.append(' </defs>\n')
    L.append(' <g id="icon">\n')
    # dark PCB, square corners; the module antenna protrudes 6.24 mm above
    L.append('  <rect x="0" y="6.24" width="27.94" height="57.15" fill="#262626" stroke="#000000" stroke-width="0.3"/>\n')
    # ESP32-S3-WROOM-1 module, horizontally centred, at the top of the board
    L.append(module_art(1.0, (27.94 - 18.0) / 2.0, 0.0, "shieldMetal"))
    # left/right 22-pin male header columns - same positions as the breadboard
    # (internal PX_L=50 / PX_R=1050 / PY0=321 / pitch 100 / r=26 at 39.37 u/mm)
    # converted to the icon's 1 unit = 1 mm scale, so the icon shows the real
    # pin columns on the long edges.
    _S = 39.37
    for _i in range(22):
        _y = (321.0 + _i * 100.0) / _S
        L.append('  <circle cx="%.3f" cy="%.3f" r="%.3f" fill="#b8b8b8" stroke="#6a6a6a" stroke-width="0.13"/>\n' % (50.0 / _S, _y, 26.0 / _S))
        L.append('  <circle cx="%.3f" cy="%.3f" r="%.3f" fill="#b8b8b8" stroke="#6a6a6a" stroke-width="0.13"/>\n' % (1050.0 / _S, _y, 26.0 / _S))
    # 2x USB-C at the bottom edge (left = OTG native USB, right = CH343p UART)
    for cx in (7.62, 20.07):
        L.append('  <rect x="%.2f" y="55.8" width="8.94" height="7.59" rx="1.2" fill="#dcdcdc" stroke="#888888" stroke-width="0.3"/>\n' % (cx - 4.47))
    L.append(' </g>\n')
    L.append('</svg>\n')
    return "".join(L)


def fzp_xml():
    conns = []
    for cn in range(44):
        name = cn_name(cn)
        desc = DESC.get(name, name)
        conns.append('  <connector id="connector%d" name="%s" type="male">\n' % (cn, name))
        conns.append('   <description>%s</description>\n' % desc)
        conns.append('   <views>\n')
        conns.append('    <breadboardView><p layer="breadboard" svgId="connector%dpin"/></breadboardView>\n' % cn)
        conns.append('    <schematicView><p layer="schematic" svgId="connector%dpin" terminalId="connector%dterminal"/></schematicView>\n' % (cn, cn))
        conns.append('    <pcbView><p layer="copper0" svgId="connector%dpin"/><p layer="copper1" svgId="connector%dpin"/></pcbView>\n' % (cn, cn))
        conns.append('   </views>\n')
        conns.append('  </connector>\n')
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<module fritzingVersion="0.9.9b" moduleId="%s">\n'
        ' <version>1</version>\n'
        ' <author>Shi Jinghai</author>\n'
        ' <title>%s</title>\n'
        ' <label>U</label>\n'
        ' <date>2026-08-26</date>\n'
        ' <tags><tag>ESP32</tag><tag>S3</tag><tag>WiFi</tag><tag>BLE</tag><tag>module</tag><tag>DevKitC</tag></tags>\n'
        ' <properties>\n'
        '  <property name="family">ESP32</property>\n'
        '  <property name="variant">ESP32-S3-DevKitC-1</property>\n'
        '  <property name="pins">44</property>\n'
        '  <property name="part number">ESP32-S3-DevKitC-1</property>\n'
        ' </properties>\n'
        ' <description>ESP32-S3-DevKitC-1 development board, 63.5x28mm, 44 pins, based on ESP32-S3-WROOM-1 (WiFi + BLE).</description>\n'
        ' <views>\n'
        '  <iconView><layers image="%s"><layer layerId="icon"/></layers></iconView>\n'
        '  <breadboardView fliphorizontal="true" flipvertical="true"><layers image="%s"><layer layerId="breadboard"/></layers></breadboardView>\n'
        '  <schematicView fliphorizontal="true" flipvertical="true"><layers image="%s"><layer layerId="schematic"/></layers></schematicView>\n'
        '  <pcbView><layers image="%s"><layer layerId="silkscreen"/><layer layerId="copper0"/><layer layerId="copper1"/></layers></pcbView>\n'
        ' </views>\n'
        ' <connectors>\n%s</connectors>\n'
        '</module>\n'
    ) % (PART_ID, TITLE, ICON_REF, BB_REF, SCHEM_REF, PCB_REF, "".join(conns))


def main():
    files = {
        BB_SVG: breadboard_svg(),
        SCHEM_SVG: schematic_svg(),
        PCB_SVG: pcb_svg(),
        ICON_SVG: icon_svg(),
        FZP: fzp_xml(),
    }
    for name, content in files.items():
        with open(os.path.join(OUT_DIR, name), "w", encoding="utf-8") as f:
            f.write(content)
        print("wrote", name)
    fzpz_dir = os.path.abspath(os.path.join(OUT_DIR, "..", "..", "fzpz"))
    os.makedirs(fzpz_dir, exist_ok=True)
    fzpz_path = os.path.join(fzpz_dir, FZPZ)
    with zipfile.ZipFile(fzpz_path, "w", zipfile.ZIP_DEFLATED) as z:
        for name in files:
            z.write(os.path.join(OUT_DIR, name), arcname=name)
    print("wrote", fzpz_path)


if __name__ == "__main__":
    main()
