# -*- coding: utf-8 -*-
"""Generate a complete Fritzing part for TS3A44159PWR (TSSOP-16 analog switch).

TS3A44159 (TI) is a bidirectional quad SPDT / dual DPDT analog switch
(1.65 V - 4.3 V), low Ron (~0.5 Ohm), break-before-make. Two digital
controls IN1-2 and IN3-4 each steer one pair of SPDT switches.

Package: PW = TSSOP-16 (PW0016A, JEDEC MO-153).
  body 5.0 x 4.4 mm, pitch 0.65 mm, 16 leads 0.17-0.30 mm wide.
  Land pattern (datasheet p.33): pad 1.5 x 0.45 mm, pitch 0.65 mm,
  pad columns 5.8 mm centre-to-centre (pad centres at +/- 2.9 mm),
  overall land-pattern width = 5.8 + 1.5 = 7.3 mm.

Pinout (PW package, from datasheet "Pin Configuration and Functions"):
    1  NO2      9  NO4
    2  COM2    10  COM4
    3  NC2     11  NC4
    4  GND     12  VCC
    5  NO3     13  NO1
    6  COM3    14  COM1
    7  NC3     15  NC1
    8  IN3-4   16  IN1-2

Connectors (connector0..15 = pin 1..16):
  connector0=NO2 connector1=COM2 connector2=NC2 connector3=GND
  connector4=NO3 connector5=COM3 connector6=NC3 connector7=IN3-4
  connector8=NO4 connector9=COM4 connector10=NC4 connector11=VCC
  connector12=NO1 connector13=COM1 connector14=NC1 connector15=IN1-2

Follows the repo part-dev-guide (docs/part-dev-guide.md) + the verified
conventions in fritzing-parts.md:
  - .fzp image refs use subdirectory paths (icon/, breadboard/, schematic/, pcb/)
  - schematic pins need class='pin'/connectorname + class='terminal'
  - PCB pads appear once, on copper1 only (SMD, no through-hole / no copper0)
  - breadboard connectors sit on the Fritzing 7.2-unit hole grid (3.6+7.2k)
  - .fzpz goes to the repo-level fzpz/ directory (flat zip, subdir refs)
"""

import os
import re
import zipfile

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
PART_ID = "TS3A44159PWR_TSSOP16_1"

# Fritzing core LM5574 TSSOP-16 breadboard, embedded here so generation is
# self-contained (no external template file needed). The black chip art is
# replaced by the real TS3A44159PWR at 1:1; the label is changed to
# TS3A44159.
LM5574_BB_TEMPLATE_SRC = r'''<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!-- Created with Fritzing (http://www.fritzing.org/) -->
<svg xmlns="http://www.w3.org/2000/svg" width="0.8in" x="0in" version="1.2" y="0in"  height="0.6in" viewBox="0 0 800 600" baseProfile="tiny" xmlns:svg="http://www.w3.org/2000/svg">
 <desc>Fritzing breadboard generated by brd2svg</desc>
 <g id="breadboard">
  <g id="icon">
   <path fill="#1F7A34" stroke="none" stroke-width="0" d="M0,0L0,270A30,30 0 0 1 0,330L0,600L800,600L800,0L0,0z"/>
   <g transform="translate(298.075,164.173)">
    <g transform="matrix(0.5, 0, 0, 0.5, 50.9626, 67.9134)">
     <rect width="15.748" x="4.48424" y="228.347" fill="#8c8c8c" connectorname="1" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="30.0747" y="228.347" fill="#8c8c8c" connectorname="2" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="55.6652" y="228.347" fill="#8c8c8c" connectorname="3" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="81.2557" y="228.347" fill="#8c8c8c" connectorname="4" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="106.846" y="228.347" fill="#8c8c8c" connectorname="5" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="132.437" y="228.347" fill="#8c8c8c" connectorname="6" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="158.027" y="228.347" fill="#8c8c8c" connectorname="7" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="183.618" y="228.347" fill="#8c8c8c" connectorname="8" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="183.618" y="0" fill="#8c8c8c" connectorname="9" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="158.027" y="0" fill="#8c8c8c" connectorname="10" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="132.437" y="0" fill="#8c8c8c" connectorname="11" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="106.846" y="0" fill="#8c8c8c" connectorname="12" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="81.2557" y="0" fill="#8c8c8c" connectorname="13" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="55.6652" y="0" fill="#8c8c8c" connectorname="14" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="30.0747" y="0" fill="#8c8c8c" connectorname="15" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="15.748" x="4.48424" y="0" fill="#8c8c8c" connectorname="16" height="43.3072" stroke="none" stroke-linecap="round" stroke-width="0"/>
     <rect width="203.85" x="0" y="45.7126" fill="#303030" height="180.228" stroke="none" stroke-width="0"/>
     <polygon fill="#1f1f1f" points="0,45.7126 203.85,45.7126 193.85,55.7126 10,55.7126"/>
     <polygon fill="#1f1f1f" points="0,225.941 203.85,225.941 193.85,215.941 10,215.941"/>
     <polygon fill="#000000" points="0,45.7126 0,225.941 10,215.941 10,55.7126"/>
     <polygon fill="#3d3d3d" points="203.85,45.7126 203.85,225.941 193.85,215.941 193.85,55.7126"/>
     <circle fill="#1f1f1f" cx="30" cy="195.941" stroke="none" r="10" stroke-width="0"/>
    </g>
   </g>
   <text x="50" y="324.375" font-family="OCRA" fill="white" text-anchor="start" stroke="none" id="label" stroke-width="0" font-size="65">TSSOP-16</text>
   <g transform="translate(63.5,526.05)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="start" stroke="none" stroke-width="0" font-size="45">1</text>
    </g>
   </g>
   <g transform="translate(63.5,73.95)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="end" stroke="none" stroke-width="0" font-size="45">16</text>
    </g>
   </g>
   <g transform="translate(163.5,526.05)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="start" stroke="none" stroke-width="0" font-size="45">2</text>
    </g>
   </g>
   <g transform="translate(163.5,73.95)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="end" stroke="none" stroke-width="0" font-size="45">15</text>
    </g>
   </g>
   <g transform="translate(263.5,526.05)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="start" stroke="none" stroke-width="0" font-size="45">3</text>
    </g>
   </g>
   <g transform="translate(263.5,73.95)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="end" stroke="none" stroke-width="0" font-size="45">14</text>
    </g>
   </g>
   <g transform="translate(363.5,526.05)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="start" stroke="none" stroke-width="0" font-size="45">4</text>
    </g>
   </g>
   <g transform="translate(363.5,73.95)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="end" stroke="none" stroke-width="0" font-size="45">13</text>
    </g>
   </g>
   <g transform="translate(463.5,526.05)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="start" stroke="none" stroke-width="0" font-size="45">5</text>
    </g>
   </g>
   <g transform="translate(463.5,73.95)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="end" stroke="none" stroke-width="0" font-size="45">12</text>
    </g>
   </g>
   <g transform="translate(563.5,526.05)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="start" stroke="none" stroke-width="0" font-size="45">6</text>
    </g>
   </g>
   <g transform="translate(563.5,73.95)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="end" stroke="none" stroke-width="0" font-size="45">11</text>
    </g>
   </g>
   <g transform="translate(663.5,526.05)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="start" stroke="none" stroke-width="0" font-size="45">7</text>
    </g>
   </g>
   <g transform="translate(663.5,73.95)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="end" stroke="none" stroke-width="0" font-size="45">10</text>
    </g>
   </g>
   <g transform="translate(763.5,526.05)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="start" stroke="none" stroke-width="0" font-size="45">8</text>
    </g>
   </g>
   <g transform="translate(763.5,73.95)">
    <g transform="rotate(-90)">
     <text x="0" y="0" font-family="OCRA" fill="white" text-anchor="end" stroke="none" stroke-width="0" font-size="45">9</text>
    </g>
   </g>
  </g>
  <g transform="translate(34.035,534.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector0pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(34.035,34.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector15pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(134.035,534.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector1pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(134.035,34.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector14pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(234.035,534.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector2pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(234.035,34.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector13pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(334.035,534.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector3pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(334.035,34.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector12pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(434.035,534.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector4pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(434.035,34.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector11pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(534.035,534.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector5pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(534.035,34.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector10pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(634.035,534.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector6pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(634.035,34.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector9pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(734.035,534.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector7pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
  <g transform="translate(734.035,34.05)">
   <rect width="31.93" x="0" y="0" fill="#8D8C8C" height="31.9" id="connector8pin"/>
   <rect width="16.4442" x="7.79153" y="7.73544" fill="#8C8663" height="16.4152"/>
   <polygon fill="#B8AF82" points="0,31.9,7.79153,24.1368,7.79153,6.97162,0,0"/>
   <polygon fill="#80795B" points="24.2079,7.76321,7.90264,7.76321,0,0,31.93,0"/>
   <polygon fill="#5E5B43" points="24.2079,24.1368,24.2079,7.76321,31.93,0,31.93,31.9"/>
   <polygon fill="#9A916C" points="0,31.9,7.87486,24.1368,24.2079,24.1368,31.93,31.9"/>
  </g>
 </g>
</svg>
'''

# View SVG filenames (flat inside fzpz)
PCB_SVG = "svg.pcb.%s_pcb.svg" % PART_ID
SCHEM_SVG = "svg.schematic.%s_schematic.svg" % PART_ID
BB_SVG = "svg.breadboard.%s_breadboard.svg" % PART_ID
ICON_SVG = "svg.icon.%s_icon.svg" % PART_ID
FZP = "part.%s.fzp" % PART_ID
FZPZ = "TS3A44159PWR.fzpz"

# .fzp image refs (subdirectory style, per guide)
PCB_REF = "pcb/%s_pcb.svg" % PART_ID
SCHEM_REF = "schematic/%s_schematic.svg" % PART_ID
BB_REF = "breadboard/%s_breadboard.svg" % PART_ID
ICON_REF = "icon/%s_icon.svg" % PART_ID

# Pin signal names, connector0..15 = pin1..16 (PW package)
PIN_NAMES = [
    "NO2", "COM2", "NC2", "GND", "NO3", "COM3", "NC3", "IN3-4",
    "NO4", "COM4", "NC4", "VCC", "NO1", "COM1", "NC1", "IN1-2",
]


# ---------------------------------------------------------------- PCB view
def pcb_svg():
    """TSSOP-16 SMD land pattern per datasheet p.33 (PW0016A).

    1 unit = 1 mm, origin = package centre. 16 copper pads 1.5 x 0.45 mm,
    pitch 0.65 mm, pad columns 5.8 mm centre-to-centre => pad centres at
    x = +/-2.9, overall land-pattern width 7.3 mm. Left column = pins 1..8
    (top->bottom), right column = pins 16..9 (top->bottom); pin 1 top-left.
    Silkscreen = top & bottom bars only (chip left-right extent +/-2.5,
    drawn clear of the pads) + pin-1 dot. SMD => copper1 only.
    """
    L = []
    L.append('<?xml version="1.0" encoding="utf-8"?>\n')
    # content x -3.65..3.65 (7.3 pad span), y -2.7..2.7 (+0.3 margin) -> 7.9 x 6.1 mm
    L.append('<svg xmlns="http://www.w3.org/2000/svg" width="7.9mm" height="6.1mm" viewBox="-3.95 -3.05 7.9 6.1">\n')
    L.append(' <g id="silkscreen">\n')
    # top & bottom bars only, showing the chip left-right extent (+/-2.5);
    # drawn outside the pad rows (pad outer edges at y=+/-2.5) -> no conflict
    L.append('  <line x1="-2.5" y1="2.7" x2="2.5" y2="2.7" stroke="#FFFFFF" stroke-width="0.15" fill="none"/>\n')
    L.append('  <line x1="-2.5" y1="-2.7" x2="2.5" y2="-2.7" stroke="#FFFFFF" stroke-width="0.15" fill="none"/>\n')
    # pin-1 index dot inside the body near pin 1 (now top-left), clear of the pads
    L.append('  <circle cx="-1.3" cy="-1.95" r="0.25" fill="#FFFFFF" stroke="none"/>\n')
    L.append(' </g>\n')
    L.append(' <g id="copper1">\n')
    PAD_W, PAD_H, PITCH, XC = 1.5, 0.45, 0.65, 2.9
    # left pads (pins 1..8, top->bottom) connector0..7; pin 1 at top (y=-2.275)
    for i in range(8):
        yc = -2.275 + i * PITCH
        L.append('  <rect x="%.3f" y="%.3f" width="%.2f" height="%.2f" id="connector%dpin" fill="#f7bf13" fill-opacity="1" stroke="none"/>\n'
                 % (-XC - PAD_W / 2, yc - PAD_H / 2, PAD_W, PAD_H, i))
    # right pads (pins 16..9, top->bottom) connector15..8; pin 16 at top
    for i in range(8):
        yc = -2.275 + i * PITCH
        cn = 15 - i
        L.append('  <rect x="%.3f" y="%.3f" width="%.2f" height="%.2f" id="connector%dpin" fill="#f7bf13" fill-opacity="1" stroke="none"/>\n'
                 % (XC - PAD_W / 2, yc - PAD_H / 2, PAD_W, PAD_H, cn))
    L.append(' </g>\n')
    L.append('</svg>\n')
    return "".join(L)


# ---------------------------------------------------------- schematic view
def schematic_svg():
    """16-pin IC symbol matching the user's hand-drawn schematic.

    Box x 90..230, y 10..310. Left pins 1..8 (NO2..IN3-4) top->bottom, right
    pins 16..9 (IN1-2..NO4) top->bottom.
    The box is split into two switch groups: IN1-2 drives SW1+SW2 (top),
    IN3-4 drives SW3+SW4 (bottom). Each SPDT switch is drawn as a mechanical
    arm: a COM lead ending in a SOLID pivot dot, a thick arm diagonal to the
    SOLID NC contact dot (normally-closed / IN=L), and a separate SOLID NO
    contact dot. Each NO/NC lead runs horizontally then bends 3/4 of the pin
    pitch toward the COM, ending in a black dot. GND (pin 4) and VCC (pin 12)
    are plain pins (no ground symbol / stub). Each IN buffer's control line
    runs HORIZONTALLY to the middle of the box, then goes VERTICALLY through
    its switch group as SOLID lines; only the short branch that drops from the
    vertical line to the MIDDLE of each switch's arm (the solid diagonal) is
    DASHED, not the pivot endpoint. Pin numbers sit just above each lead line;
    signal names sit at the box edges next to their pins.
    """
    L = []
    L.append('<?xml version="1.0" encoding="utf-8"?>\n')
    L.append('<svg xmlns="http://www.w3.org/2000/svg" width="212" height="320" viewBox="55 0 212 320">\n')
    L.append(' <g id="schematic">\n')
    BX, BY, BW, BH = 90, 10, 140, 300
    L.append('  <rect x="%d" y="%d" width="%d" height="%d" fill="#FFFFFF" stroke="#000000" stroke-width="1.6"/>\n' % (BX, BY, BW, BH))
    # ---- 4 SPDT switches (mechanical-arm style) ----
    # (NO_y, COM_y, NC_y, side); the arm is drawn to the NC contact (IN=L).
    switches = [
        (20, 60, 100, 'L'),    # SW2: NO2(1) COM2(2) NC2(3)
        (180, 220, 260, 'L'),  # SW3: NO3(5) COM3(6) NC3(7)
        (140, 100, 60, 'R'),   # SW1: NO1(13) COM1(14) NC1(15)
        (300, 260, 220, 'R'),  # SW4: NO4(9) COM4(10) NC4(11)
    ]
    DOT = 2.5
    BEND = 30  # 3/4 of the 40-unit pin pitch; each outer contact bends toward COM
    for (y_no, y_com, y_nc, side) in switches:
        if side == 'L':
            ex, cdot, cpiv = 90, 130, 118
        else:
            ex, cdot, cpiv = 230, 190, 202
        # outer contacts bend toward the COM, ending in a black dot
        y_no_dot = y_no + BEND if y_no < y_com else y_no - BEND
        y_nc_dot = y_nc + BEND if y_nc < y_com else y_nc - BEND
        # NO lead: horizontal then L-bend (down if NO is above COM, else up)
        L.append('  <line x1="%d" y1="%d" x2="%d" y2="%d" stroke="#000000" stroke-width="1.2" fill="none"/>\n' % (ex, y_no, cdot, y_no))
        L.append('  <line x1="%d" y1="%d" x2="%d" y2="%d" stroke="#000000" stroke-width="1.2" fill="none"/>\n' % (cdot, y_no, cdot, y_no_dot))
        # NC lead: horizontal then L-bend (up if NC is below COM, else down)
        L.append('  <line x1="%d" y1="%d" x2="%d" y2="%d" stroke="#000000" stroke-width="1.2" fill="none"/>\n' % (ex, y_nc, cdot, y_nc))
        L.append('  <line x1="%d" y1="%d" x2="%d" y2="%d" stroke="#000000" stroke-width="1.2" fill="none"/>\n' % (cdot, y_nc, cdot, y_nc_dot))
        # COM lead to the pivot
        L.append('  <line x1="%d" y1="%d" x2="%d" y2="%d" stroke="#000000" stroke-width="1.2" fill="none"/>\n' % (ex, y_com, cpiv, y_com))
        # mechanical arm: COM pivot -> NC contact dot (thick)
        L.append('  <line x1="%d" y1="%d" x2="%d" y2="%d" stroke="#000000" stroke-width="2.2" fill="none"/>\n' % (cpiv, y_com, cdot, y_nc_dot))
        # solid contact / pivot dots
        L.append('  <circle cx="%d" cy="%d" r="%d" fill="#000000" stroke="none"/>\n' % (cdot, y_no_dot, DOT))
        L.append('  <circle cx="%d" cy="%d" r="%d" fill="#000000" stroke="none"/>\n' % (cpiv, y_com, DOT))
        L.append('  <circle cx="%d" cy="%d" r="%d" fill="#000000" stroke="none"/>\n' % (cdot, y_nc_dot, DOT))
    # GND (pin 4) and VCC (pin 12) are plain pins - no internal symbol/stub
    # ---- control-input buffers (triangles) + control lines ----
    # Each IN buffer's control line runs HORIZONTALLY to the middle of the
    # box, then goes VERTICALLY through its switch group as SOLID lines; only
    # the short branches dropping to the MIDDLE of each switch's arm (the solid
    # diagonal) are DASHED, not the pivot endpoint.
    # IN1-2 (pin 16, right y=20): buffer points left
    L.append('  <line x1="230" y1="20" x2="197" y2="20" stroke="#000000" stroke-width="1.2" fill="none"/>\n')
    L.append('  <polygon points="197,13 197,27 185,20" fill="#FFFFFF" stroke="#000000" stroke-width="1.2"/>\n')
    # horizontal to the middle, then down through the top group (solid)
    L.append('  <line x1="185" y1="20" x2="160" y2="20" stroke="#000000" stroke-width="1.2" fill="none"/>\n')
    L.append('  <line x1="160" y1="20" x2="160" y2="95" stroke="#000000" stroke-width="1.2" fill="none"/>\n')
    # branches to the arm MIDDLES (DASHED): SW2 (124,65), SW1 (196,95)
    L.append('  <line x1="160" y1="65" x2="124" y2="65" stroke="#000000" stroke-width="1.0" stroke-dasharray="4 4" fill="none"/>\n')
    L.append('  <line x1="160" y1="95" x2="196" y2="95" stroke="#000000" stroke-width="1.0" stroke-dasharray="4 4" fill="none"/>\n')
    # IN3-4 (pin 8, left y=300): buffer points right
    L.append('  <line x1="90" y1="300" x2="122" y2="300" stroke="#000000" stroke-width="1.2" fill="none"/>\n')
    L.append('  <polygon points="122,293 122,307 134,300" fill="#FFFFFF" stroke="#000000" stroke-width="1.2"/>\n')
    # horizontal to the middle, then up through the bottom group (solid)
    L.append('  <line x1="134" y1="300" x2="160" y2="300" stroke="#000000" stroke-width="1.2" fill="none"/>\n')
    L.append('  <line x1="160" y1="300" x2="160" y2="225" stroke="#000000" stroke-width="1.2" fill="none"/>\n')
    # branches to the arm MIDDLES (DASHED): SW4 (196,255), SW3 (124,225)
    L.append('  <line x1="160" y1="255" x2="196" y2="255" stroke="#000000" stroke-width="1.0" stroke-dasharray="4 4" fill="none"/>\n')
    L.append('  <line x1="160" y1="225" x2="124" y2="225" stroke="#000000" stroke-width="1.0" stroke-dasharray="4 4" fill="none"/>\n')
    # ---- left pins 1..8 (connector0..7), top->bottom ----
    for i in range(8):
        y = 20 + i * 40
        L.append('  <line class="pin" id="connector%dpin" connectorname="%d" x1="%d" y1="%.0f" x2="%d" y2="%.0f" stroke="#787878" stroke-width="1.0"/>\n' % (i, i + 1, BX, y, 68, y))
        L.append('  <rect class="terminal" id="connector%dterminal" x="68" y="%.0f" width="0.0001" height="0.0001" fill="none"/>\n' % (i, y))
        L.append('  <text x="84" y="%.0f" font-size="5.5" fill="#8C8C8C" text-anchor="middle" font-family="DroidSans">%d</text>\n' % (y - 4, i + 1))
        L.append('  <text x="96" y="%.0f" font-size="5.5" fill="#000000" text-anchor="start" font-family="DroidSans">%s</text>\n' % (y - 2, PIN_NAMES[i]))
    # ---- right pins 16..9 (connector15..8), top->bottom ----
    for i in range(8):
        y = 20 + i * 40
        cn = 15 - i
        num = 16 - i
        L.append('  <line class="pin" id="connector%dpin" connectorname="%d" x1="%d" y1="%.0f" x2="%d" y2="%.0f" stroke="#787878" stroke-width="1.0"/>\n' % (cn, num, BX + BW, y, 252, y))
        L.append('  <rect class="terminal" id="connector%dterminal" x="252" y="%.0f" width="0.0001" height="0.0001" fill="none"/>\n' % (cn, y))
        L.append('  <text x="238" y="%.0f" font-size="5.5" fill="#8C8C8C" text-anchor="middle" font-family="DroidSans">%d</text>\n' % (y - 4, num))
        L.append('  <text x="224" y="%.0f" font-size="5.5" fill="#000000" text-anchor="end" font-family="DroidSans">%s</text>\n' % (y - 2, PIN_NAMES[cn]))
    L.append(' </g>\n')
    L.append('</svg>\n')
    return "".join(L)


# --------------------------------------------------------- breadboard view
def _chip_art_block():
    """The REAL TS3A44159PWR at 1:1 scale (1 mm = 39.37 breadboard units),
    rotated 90 deg CCW so the leads/pads sit on the top (16..9) and bottom
    (1..8) rows (matching the template's connector rows), centred at (400,300).

    No distortion / no forced alignment: body 4.4 x 5.0 mm, 16 gold SMD leads
    (0.24 x 1.0 mm), 16 gold PCB pads (1.5 x 0.45 mm, pitch 0.65 mm), pin-1
    marker and YC4159 marking -- all at true 1:1 proportions.
    """
    MM = 39.3701
    cx, cy = 400.0, 300.0
    bx, by = cx - 5.0 * MM / 2, cy - 4.4 * MM / 2          # rotated body 5.0 x 4.4
    bw, bh = 5.0 * MM, 4.4 * MM
    pitch = 0.65 * MM
    xc = lambda k: cx - 3.5 * pitch + k * pitch            # 8 rows centred on cx
    L = ['   <g>\n']
    L.append('    <rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" rx="%.2f" ry="%.2f" fill="#303030" stroke="none"/>\n'
             % (bx, by, bw, bh, 0.1 * MM, 0.1 * MM))
    # 16 PCB pads 1.5 x 0.45 mm (rotated -> width 0.45, height 1.5) in GRAY so
    # they can be told apart from the gold SMD leads/pins
    pw, ph = 0.45 * MM, 1.5 * MM
    for k in range(8):
        x = xc(k) - pw / 2
        L.append('    <rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" fill="#8c8c8c" stroke="none"/>\n'
                 % (x, cy - 2.9 * MM - ph / 2, pw, ph))   # top pad (16-k)
        L.append('    <rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" fill="#8c8c8c" stroke="none"/>\n'
                 % (x, cy + 2.9 * MM - ph / 2, pw, ph))   # bottom pad (k+1)
    # 16 gold SMD leads 0.24 x 1.0 mm (rotated -> width 0.24, height 1.0)
    lw, lh = 0.24 * MM, 1.0 * MM
    for k in range(8):
        x = xc(k) - lw / 2
        L.append('    <rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" fill="#f7bf13" stroke="none"/>\n'
                 % (x, by - lh, lw, lh))                  # top lead (16-k)
        L.append('    <rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" fill="#f7bf13" stroke="none"/>\n'
                 % (x, by + bh, lw, lh))                  # bottom lead (k+1)
    # pin-1 marker, placed on the body to match the ICON's pin-1 circle
    # (the icon circle sits at ~17.5% from the body left, ~82% down -> here it
    # lands above the pin-2 pad, clearly clear of the bottom pad row)
    L.append('    <circle cx="%.2f" cy="%.2f" r="8" fill="#c0c0c0" stroke="none"/>\n'
             % (bx + 0.175 * bw, by + 0.818 * bh))
    L.append('    <text x="%.2f" y="%.2f" font-size="22" font-family="DroidSans" fill="#c0c0c0" text-anchor="middle" stroke="none" stroke-width="0">YC4159</text>\n' % (cx, cy + 8))
    L.append('   </g>\n')
    return ''.join(L)


def breadboard_svg():
    """TS3A44159PWR breadboard based on the Fritzing core LM5574 TSSOP-16
    template: the template's stylised black chip + gray pads are replaced by
    the REAL part at 1:1 scale (see _chip_art_block). The green board, the
    metallic connector pins, the pin numbers and the part label are kept.
    viewBox 0 0 800 600 (core Fritzing breadboard scale).
    """
    src = LM5574_BB_TEMPLATE_SRC
    # replace the whole inner chip group (gray pads + black chip) with the 1:1 part
    start = src.index('   <g transform="translate(298.075,164.173)">\n')
    end_marker = '    </g>\n   </g>\n'
    end = src.index(end_marker, start) + len(end_marker)
    src = src[:start] + _chip_art_block() + src[end:]
    # part label: TS3A44159 (static), below the chip, clear of the pads
    label_line = ('   <text x="50" y="324.375" font-family="OCRA" fill="white" '
                  'text-anchor="start" stroke="none" id="label" stroke-width="0" '
                  'font-size="65">TSSOP-16</text>')
    new_label = ('   <text x="400" y="485" font-family="OCRA" fill="white" '
                 'text-anchor="middle" stroke="none" stroke-width="0" '
                 'font-size="45">TS3A44159</text>')
    assert label_line in src, 'label line not found in LM5574 template'
    src = src.replace(label_line, new_label)
    return src


# ---------------------------------------------------------------- icon view
def icon_svg():
    """32x32 icon matching datasheet p.32 PW package outline, rotated 90 deg
    counter-clockwise (so the chip is horizontal with leads on top/bottom).

    4 units/mm. Body 4.4 x 5.0 mm (17.6 x 20.0) with small rounded corners
    (rx/ry 0.4 = 0.1 mm), centred at (16,16). 8 leads per side, lead width
    0.24 mm (0.96) and length 1.0 mm (4.0) -> overall width incl. leads
    6.4 mm (25.6). Pin 1 index = solid circle (r 1.4). The whole icon is
    wrapped in rotate(-90 16 16) so pins point up/down (16..9 top, 1..8
    bottom), matching the breadboard layout.
    """
    L = []
    L.append('<?xml version="1.0" encoding="UTF-8"?>\n')
    L.append('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">\n')
    L.append(' <g id="icon" transform="rotate(-90 16 16)">\n')
    # chip body 4.4 x 5.0 mm, small rounded corners (rx=ry=0.4 = 0.1 mm)
    BX, BY, BW, BH = 7.2, 6.0, 17.6, 20.0
    L.append('  <rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" rx="0.4" ry="0.4" fill="#303030" stroke="none"/>\n' % (BX, BY, BW, BH))
    # 8 leads per side: width 0.24 mm (0.96), length 1.0 mm (4.0), pitch 0.65 mm (2.6)
    PW = 0.96  # lead thickness (0.24 mm)
    PL = 4.0   # lead length (1.0 mm)
    for i in range(8):
        yc = 16.0 - 9.1 + i * 2.6  # pin centres span 18.2 (4.55 mm), centred on 16
        L.append('  <rect x="%.1f" y="%.2f" width="%.1f" height="%.2f" fill="#f7bf13" stroke="none"/>\n' % (BX - PL, yc - PW / 2, PL, PW))
        L.append('  <rect x="%.1f" y="%.2f" width="%.1f" height="%.2f" fill="#f7bf13" stroke="none"/>\n' % (BX + BW, yc - PW / 2, PL, PW))
    # pin-1 index solid circle (r 1.4 = 2x), to the right of pin 2 (y=9.5),
    # moved right one radius from (9.0,9.5) to (10.4,9.5)
    L.append('  <circle cx="10.4" cy="9.5" r="1.4" fill="#c0c0c0" stroke="none"/>\n')
    # marking text (device top-mark code), rotated 90 deg CW around its
    # visual centre (16, 15.5) so the vertical label stays centred on x=16
    L.append('  <text x="16" y="16.6" font-size="3.0" font-family="DroidSans" fill="#c0c0c0" text-anchor="middle" stroke="none" stroke-width="0" transform="rotate(90 16 15.5)">YC4159</text>\n')
    L.append(' </g>\n')
    L.append('</svg>\n')
    return "".join(L)


# ------------------------------------------------------------------ .fzp
def fzp_xml():
    conns = []
    for cn in range(16):
        name = PIN_NAMES[cn]
        conns.append(
            '  <connector id="connector%d" name="%s" type="male">\n'
            '   <description>Pin %d - %s</description>\n'
            '   <views>\n'
            '    <breadboardView><p layer="breadboard" svgId="connector%dpin"/></breadboardView>\n'
            '    <schematicView><p layer="schematic" svgId="connector%dpin" terminalId="connector%dterminal"/></schematicView>\n'
            '    <pcbView><p layer="copper1" svgId="connector%dpin"/></pcbView>\n'
            '   </views>\n'
            '  </connector>\n' % (cn, name, cn + 1, name, cn, cn, cn, cn))
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<module fritzingVersion="0.9.9b" moduleId="%s">\n'
        ' <version>1</version>\n'
        ' <author>Shi Jinghai</author>\n'
        ' <title>TS3A44159PWR</title>\n'
        ' <label>U</label>\n'
        ' <date>2026-08-27</date>\n'
        ' <tags><tag>IC</tag><tag>analog</tag><tag>switch</tag><tag>TS3A44159</tag><tag>TSSOP-16</tag></tags>\n'
        ' <properties>\n'
        '  <property name="family">switch</property>\n'
        '  <property name="part number">TS3A44159PWR</property>\n'
        '  <property name="package">TSSOP-16</property>\n'
        '  <property name="pins">16</property>\n'
        ' </properties>\n'
        ' <description>Quad SPDT / dual DPDT bidirectional analog switch, 1.65-4.3 V, TSSOP-16 (PW).</description>\n'
        ' <views>\n'
        '  <iconView>\n'
        '   <layers image="%s">\n'
        '    <layer layerId="icon"/>\n'
        '   </layers>\n'
        '  </iconView>\n'
        '  <breadboardView fliphorizontal="true" flipvertical="true">\n'
        '   <layers image="%s">\n'
        '    <layer layerId="breadboard"/>\n'
        '   </layers>\n'
        '  </breadboardView>\n'
        '  <schematicView fliphorizontal="true" flipvertical="true">\n'
        '   <layers image="%s">\n'
        '    <layer layerId="schematic"/>\n'
        '   </layers>\n'
        '  </schematicView>\n'
        '  <pcbView>\n'
        '   <layers image="%s">\n'
        '    <layer layerId="silkscreen"/>\n'
        '    <layer layerId="copper1"/>\n'
        '   </layers>\n'
        '  </pcbView>\n'
        ' </views>\n'
        ' <connectors>\n'
        '%s'
        ' </connectors>\n'
        '</module>\n'
    ) % (PART_ID, ICON_REF, BB_REF, SCHEM_REF, PCB_REF, "".join(conns))


# -------------------------------------------------- schematic 裁边 (trim)
def _num_attrs(tag, names):
    out = {}
    for n in names:
        m = re.search(r'\b%s="(-?[\d.]+)"' % n, tag)
        if m:
            out[n] = float(m.group(1))
    return out


def content_bbox(text):
    xs, ys = [], []
    for m in re.finditer(r'<(rect|circle|ellipse|line|polygon|polyline|path|text)(\b[^>]*?)/?>', text):
        tag, attrs = m.group(1), m.group(2)
        a = _num_attrs(attrs, ["x", "y", "cx", "cy", "r", "rx", "ry", "x1", "y1", "x2", "y2", "width", "height"])
        if tag == "rect":
            if "x" in a and "y" in a:
                xs += [a["x"], a["x"] + a.get("width", 0)]
                ys += [a["y"], a["y"] + a.get("height", 0)]
        elif tag in ("circle", "ellipse"):
            if "cx" in a and "cy" in a:
                r = a.get("r", max(a.get("rx", 0), a.get("ry", 0)))
                xs += [a["cx"] - r, a["cx"] + r]; ys += [a["cy"] - r, a["cy"] + r]
        elif tag == "line":
            for k in ("x1", "x2"):
                if k in a: xs.append(a[k])
            for k in ("y1", "y2"):
                if k in a: ys.append(a[k])
        elif tag in ("polygon", "polyline"):
            pts = re.search(r'\bpoints="([^"]+)"', attrs)
            if pts:
                nums = [float(z) for z in re.findall(r'-?[\d.]+', pts.group(1))]
                xs += nums[::2]; ys += nums[1::2]
        elif tag == "text":
            if "x" in a: xs.append(a["x"])
            if "y" in a: ys.append(a["y"])
    return (min(xs), min(ys), max(xs), max(ys))


def _shift_attr(tag, sx, sy):
    def sh(attr, dx, dy):
        def rep(m):
            v = float(m.group(1)) - (dx if attr in ("x", "cx", "x1", "x2") else dy)
            return f'{attr}="{v:.4f}"'
        return re.sub(r'\b%s="(-?[\d.]+)"' % attr, rep, tag)
    for attr in ("x", "y", "cx", "cy", "x1", "y1", "x2", "y2"):
        tag = sh(attr, sx, sy)
    return tag


def trim_svg(text, margin=3.0):
    """裁边: shift content so its bbox starts at `margin` and set the svg
    width/height/viewBox to "0 0 W H" (content + 2*margin). Preserves
    self-closing tags. Returns (new_text, bbox, shift, size)."""
    mnx, mny, mxx, mxy = content_bbox(text)
    sx, sy = mnx - margin, mny - margin
    w, h = (mxx - mnx) + 2 * margin, (mxy - mny) + 2 * margin

    def shift_element(m):
        tag, attrs, selfclose = m.group(1), m.group(2), m.group(3)
        attrs2 = _shift_attr(attrs, sx, sy)
        pm = re.search(r'\bpoints="([^"]+)"', attrs2)
        if pm and tag in ("polygon", "polyline"):
            nums = [float(z) for z in re.findall(r'-?[\d.]+', pm.group(1))]
            new = []
            for i in range(0, len(nums), 2):
                new.append(f"{nums[i] - sx:.4f},{nums[i + 1] - sy:.4f}")
            attrs2 = re.sub(r'\bpoints="[^"]+"', f'points="{" ".join(new)}"', attrs2)
        return f"<{tag}{attrs2}{selfclose}>"

    out = re.sub(r'<(rect|circle|ellipse|line|polygon|polyline|path|text)(\b[^>]*?)(/?)>', shift_element, text)
    out = re.sub(r'\bviewBox="[^"]*"', f'viewBox="0 0 {w:.4f} {h:.4f}"', out, count=1)
    out = re.sub(r'\bwidth="[^"]*"', f'width="{w:.4f}"', out, count=1)
    out = re.sub(r'\bheight="[^"]*"', f'height="{h:.4f}"', out, count=1)
    return out, (mnx, mny, mxx, mxy), (sx, sy), (w, h)


def main():
    files = {
        PCB_SVG: pcb_svg(),
        SCHEM_SVG: trim_svg(schematic_svg())[0],
        BB_SVG: breadboard_svg(),
        ICON_SVG: icon_svg(),
        FZP: fzp_xml(),
    }
    for name, content in files.items():
        with open(os.path.join(OUT_DIR, name), "w", encoding="utf-8") as f:
            f.write(content)
        print("wrote", name)

    fzpz_dir = os.path.abspath(os.path.join(OUT_DIR, "..", "..", "fzpz"))
    os.makedirs(fzpz_dir, exist_ok=True)
    fzpz_path = os.path.join(fzpz_dir, FZPZ)
    with zipfile.ZipFile(fzpz_path, "w", zipfile.ZIP_DEFLATED) as z:
        for name in files:
            z.write(os.path.join(OUT_DIR, name), arcname=name)
    print("wrote", fzpz_path)


if __name__ == "__main__":
    main()
